name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main # ou 'master', dependendo do seu branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Use uma versão do Python que você preferir

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run build script
      run: python build_portfolio.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Publica o conteúdo da pasta 'dist'
        # user_name: 'github-actions[bot]' # Opcional: para commits do bot
        # user_email: 'github-actions[bot]@users.noreply.github.com' # Opcional